# Generated by Django 4.2.1 on 2023-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_proyect', models.CharField(max_length=50, verbose_name='name for the proyect')),
                ('description', models.CharField(max_length=200)),
                ('category_proyects', models.CharField(choices=[('WO', 'Work'), ('ST', 'Study'), ('LI', 'Life')], default='LI', max_length=2)),
            ],
        ),
    ]
