# Generated by Django 4.2.1 on 2023-05-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyects',
            new_name='Proyect',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50, verbose_name='name for the task')),
                ('description', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('status_task', models.CharField(choices=[('DO', 'Done'), ('PE', 'Pending'), ('IN', 'In progress')], default='PE', max_length=2)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyects.proyect')),
            ],
        ),
    ]
