# Generated by Django 4.2.1 on 2023-05-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0002_rename_proyects_proyect_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyect',
            options={'ordering': ['name_proyect'], 'verbose_name': 'Proyect', 'verbose_name_plural': 'Proyects'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['date'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
    ]
